spring:
  config:
    activate:
      on-profile: docker
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:postgresql://backend-db:5432/sgu
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.auth-server-url}realms/${keycloak.realm}/protocol/openid-connect/certs
keycloak:
  auth-server-url: http://keycloak:8080/
  realm: sgu-ufape
  client-secret: iIueertdxnoPmpoA1Fsy6BfjMVbEa1d5
  client-id: sgu-application


eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: sgu-auth-service
    prefer-ip-address: false