# Para rodar localmente sem o git utilize o comando comentado abaixo no lugar do config.server.git,
# isso é recomendado para desenvolvimento, já que dá para mudar dinamicamente o arquivo sem precisar fazer o commit:

spring:
  application:
    name: sgu-config-service

  profiles:
    active: native

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/lmtsufape/sgu-config-service
#          default-label: main
#          clone-on-start: true
#          basedir: /tmp/config-repo
#          search-paths: src/main/resources/config-repo

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
management:
  endpoints:
    web:
      exposure:
        include: health, info

server:
  port: 8888